site_name: UltraNX-Wiki
site_url: https://icephoenix2456.github.io/Ultra_wiki/
theme:
  name: material
  language: ru
  features:
    - navigation.instant.progress
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - toc.follow
    - navigation.top
    - header.autohide
    - search.suggest
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.toc:
      slugify: !!python/name:slugify.slugify
      permalink: true